import { Layout } from '@components/common';
import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

Home.Layout = Layout

export default Home;
