import { AuthView } from '@components/auth'
import { Layout } from '@components/common'
import Loading from '@components/common/Loading'
import { Post } from '@components/post'
import { Container } from '@components/ui'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

const Home = () => {
  const { data, status } = useSession()
  console.log(data)

  if (status === 'loading') return <Loading />

  if (status === 'unauthenticated') return <AuthView />

  return (
    <Container>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Post />
      </Layout>
    </Container>
  )
}

export default Home
